local.mouseisdown=0;local.current={};local.data={};local.counter={};function mouseposition(a){if(!a)a=window.event;local.mouseX=a.clientX;local.mouseY=a.clientY}
function initializer(){onHashChange();showtime(time);document.onmousedown=mouseposition;$("ajaxloader").hide();$("searchform").onsubmit=function(){return!1};$("searchtext").onblur=function(){hide_search()};$("searchtext").onfocus=function(){hold_search()};$("close_info").onclick=function(){close_info()};var a=switcher("initializer",here.page);if(a)window[a]();if(a=switcher("update_information",here.page))window[a]();close_shutter()}
function eventloader(a){a==void 0&&(a=$(document.body));a.select(".event_hidelast").each(function(a){a.observe("mouseover",function(){this.lastChild.removeClassName("hidden")});a.observe("mouseout",function(){this.lastChild.addClassName("hidden")});$(a.lastChild).addClassName("hidden")});a.select(".event_hidefirst").each(function(a){a.observe("mouseover",function(){this.firstChild.removeClassName("hidden")});a.observe("mouseout",function(){this.firstChild.addClassName("hidden")});$(a.firstChild).addClassName("hidden")});
you.browser!=="gc"&&a.select(".link").each(function(a){a.observe("mouseover",function(){Element.addClassName(this,"highlighted_element")});a.observe("mouseout",function(){Element.removeClassName(this,"highlighted_element")})});var b=switcher("eventloader",here.page);if(b)window[b](a);return a}document.observe("dom:loaded",function(){initializer();eventloader()});function showtime(a){try{var b=(new Date).getTime()/1E3-a;$("loadtime").update(String(Math.round(b*1E5)/1E5)+"s")}catch(c){}}
function gui_wrong(a){msg(a)}function gui_error(a){msg(a)}function gui_ajaxcatch(a){var b=$("ajaxloader");a===0?b.show():a===8&&b.hide();hid=window.setTimeout(function(){$("ajaxloader").hide()},5E3)}function gui_request_error(a){if(DEBUG!=1){if(func=switcher("show_error_"+a.errnum,a.errloc))window[func](a.errloc);return!1}var b="DEBUG ERROR ";b+=la["err_"+a.errnum]?la["err_"+a.errnum]:la.err_unknown;b+=" - "+a.errnum+": "+a.errname+" @ "+a.errloc+" - "+a.lastquery;msg(b)}
function gui_load_hash(){clear_data();tab_switch(here.page,1)}function gui_refresh_here(a){if(a==="registerid")clear_data(["save","tag","verb","person","form"]),local.cached_overview=0}function msg(a){a='<div class="popup_inner">'+a+'</div><form action="javascript: return false"><input id="ok_button" type="button" value="'+la.ok+'" onclick="close_popup()"></form>';$("popup").update(a);do_popup();$("ok_button").focus()}
function ask(a,b){input=a+"<form action='javascript: return false' name='popup_form' id='popup_form'><input type='button' onclick='close_popup(); "+b+"' id='popup_yes' value='"+la[1]+"'><input type='button' onclick='close_popup()' id='popup_no' value='"+la[0]+"'></form>";$("popup").update(input);do_popup();$("popup_yes").focus()}function firstelement(a){return typeof a==="object"?a[0]:a}
function formfield2id(a,b){var c=$(a);if(!c||typeof c!=="object")return!1;c=c.serialize(!0)[b];return c===void 0?(msg(la.err_209),null):c}function get_name(a,b){var c=local.data[a].id.indexOf(b);return local.data[a].name[c]}function get_key(a){var b;if(a)if(window.event)b=a.keyCode;else if(a.which)b=a.which;return b}function getposition(a){var b=0,c=0;do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent);return[b,c]}
function get_here(){var a={},b;for(b in here)here[b]&&(a[b]=here[b]);return a}function switcher(a,b){try{return typeof window[a+"_"+b+"_"+here.page]==="function"?a+"_"+b+"_"+here.page:typeof window[a+"_"+b]==="function"?a+"_"+b:typeof window[a+"_generic_"+here.page]==="function"?a+"_generic_"+here.page:typeof window[a+"_generic"]==="function"?a+"_generic":!1}catch(c){msg("[switcher]:"+c)}}function close_action(a,b,c){if(a=switcher("close_"+a,b))window[a](c)}
function send_input(a,b,c,d){var e=switcher("send_"+c,b);if(e)window[e](a,b,d,c)}function after_send(a,b,c){try{clear_data(c.type);if(!c.key)c.key=0;var d="after_send_"+c.action+"_"+c.key,e=switcher(d,c.type);if(!e)throw"[0] no function found for: type = "+c.type+" - function should have this name: "+d+"_<type>";window[e](a,b,c.id,c.type,c.where)}catch(f){msg("[after_send]:"+f),errnum=1}}
function fill(a,b){try{var c=switcher("fill_"+b,a);if(!c)throw"[0] no function found for: "+a;return c}catch(d){msg("[fill]:"+d),errnum=1}}function load_data(a,b,c){try{var d=switcher("load_data",c);if(!d)throw"[0] no function found for: "+c;window[d](a,b,c)}catch(e){msg("[load_data]:"+e),errnum=1}}function input_keydown(a,b,c,d){var e;if(d)if(window.event)e=d.keyCode;else if(d.which)e=d.which;if(d=switcher("input_keydown_"+e,b))window[d](a,b,c)}
function input_keyup(a,b,c,d){var e;if(d)if(window.event)e=d.keyCode;else if(d.which)e=d.which;if(d=switcher("input_keyup_"+e,b))window[d](a,b,c)}function get_function_writeone(a){var b={location:"php/write_one.php"};b["function"]="write_one_"+a;return b}function put_list(a,b){if(!b)return!1;b.insert({after:a});eventloader(b.up());b.remove()}
function cleaner(a,b){try{if(a===void 0||a===null)throw"[0] first parameter: id is null.";if(b===void 0||b===null)throw"[1] second parameter: type is null.";var c=[];nid=typeof a!=="object"?[a]:a;for(var d=0;d<nid.length;d++){if(here[b+"id"]==nid[d]){location.reload();break}var e=$$("."+b+"_"+nid[d]+"_remove");c.push(e.length!=0);e.each(function(a){a.remove()});clear_data(b)}return c.length==1?c[0]:c}catch(f){msg("[cleaner]:"+f),errnum=1}}
function appender(a,b,c,d){try{Object.isElement(c)||debug.warning('"where" is not defined (correctly). should be a html element.');b||debug.warning('"type" is not defined.');var d=d!=null?d:"before",e={};e[d]=a;var f=Element.insert(c,e);if(d=="after"||d=="before")f=f.parentNode;typeof eventloader=="function"&&eventloader(f);clear_data(b)}catch(g){msg("[appender]:"+g),errnum=1}}
function g_dropdown(a,b,c,d,e){try{for(var f="",g=0,h=0;h<c.length;h++)if(c[h]=="hr")f+="<hr>";else if(c[h]=="list")f+='<li id="dropdown_list_loading">'+la.loading+"</li>",g=1;else{var j=switcher("link_"+c[h],a);if(j)f+=window[j](b,a);else if(j=switcher("dropdown_action",a))f+=window[j](c[h],b,a,d);else throw"[0] no function found for: "+a;}e!=null?load_dropdown(e,"<ul>"+f+"</ul>"):load_dropdown_mouse("<ul>"+f+"</ul>");g==1&&load_data("list",$("dropdown_list_loading"),a)}catch(k){msg("[g_dropdownn]:"+
k),errnum=1}}function do_action(a,b,c,d){try{hide_dropdown(0);close_action(c,b);var e=switcher("action_"+c,b);if(!e)throw"[0] no function found for: "+c;window[e](a,b,d)}catch(f){msg("[do_action]:"+f+'<br> tried to call: "'+e+'"'),errnum=1}}
function load_data_generic(a,b,c){try{var d=fill(c,a);if(d)if(local.data[c])window[d](b,c);else{var e=Object.clone(get_here());e.count=1;e[c+"id"]=null;req("get_"+c,e,function(a,b,c){local.data[c[1]]=a;window[c[2]](c[0],c[1])},[b,c,d])}else b.update(la.err_102)}catch(f){msg("[load_data_generic]:"+f)}}
function load_data_group(a,b){try{var c=fill("group",a);if(local.data.group)window[c](b,"group");else req("get_reg_info",here,function(a,b,c){local.data.group=a;window[c[0]](c[1],"group")},[c,b])}catch(d){msg("[load_data_group]:"+d)}return!1}function load_data_wordclass(a,b){window[fill("wordclass",a)](b,"wordclass")}function load_data_column(a,b){window[fill("column",a)](b,"column")}
function dropdown_action_generic(a,b,c,d){try{Object.isElement(d)||debug.warning("where is not defined as an Element");var e=$(d).identify();return'<li class="link menulink action_'+a+'" onclick="do_action(\''+b+"','"+c+"','"+a+"',$('"+e+"'));\">"+la[a]+"</li>"}catch(f){msg("[dropdown_action_generic]:"+f),errnum=1}}function fill_list_generic(a,b){for(var c="",d=local.data[b],e=0;e<d.count;e++){var f=switcher("link_goto",b);c+=window[f](d.id[e],b,d.name[e])}put_list(c,a);position_dropdown()}
function fill_list_group(a){for(var b="",c=switcher("link_goto","group"),d=1;d<=local.data.group.groupcount;d++)b+=window[c](d,"group",la.group+" "+d);b+=window[c]("af","group",la.af);b+=window[c]("ar","group",la.ar);put_list(b,a);position_dropdown()}
function fill_list_column(a){var b="";$$('th[id$="_head"]').each(function(a){if(a.getStyle("display")=="none"&&(a=a.identify().slice(0,-5),a!="register"||here.registerid==null))b+="<li class='menulink link' onclick='displaycolumn(1,\""+a+"\")'>"+$(a+"_span_head").innerHTML+"</li>"});b==""?hide_dropdown(0):(put_list(b,a),position_dropdown())}
function fill_list_wordclass(a){for(var b="",c=0;c<6;c++)b+="<li class='menulink link' onclick='do_action(\""+c+'","wordclass","goto")\'>'+la.classname[c]+"</li>";put_list(b,a);position_dropdown()}function action_goto_generic(a,b,c){do_shutter(1);b!="word"&&clear_here("wordid");b=="tag"&&clear_here("keyoption");c===void 0&&(c={},c[b+"id"]=a);location.href=path(c)}
action_force_goto_keyoption=action_goto_keyoption=function(a){do_shutter(1);a=="verb"&&clear_here(["formid","personid","wordid"]);location.href=path({keyoption:a})};function action_goto_word(a){update_here({keyoption:"show"});clear_here(["formid","personid","wordclassid","tagid","groupid","withoutid","searchid","saveid"]);action_goto_generic(a,"word")}
function action_goto_verb(a,b){do_shutter(1);clear_here(["wordid","personid","formid"]);var c={keyoption:"verb"};c[(b=="verb"?"word":b)+"id"]=a;location.href=path(c)}function action_goto_person(a){action_goto_verb(a,"person")}function action_goto_form(a){action_goto_verb(a,"form")}function action_goto_search(a){clear_here(["queryid","keyoption"]);update_here({searchtext:"like: "+a});action_goto_generic(a,"search")}
function action_force_goto_generic(a,b){do_shutter(1);var c={};c[b+"id"]=a;location.href=path(1,c)}function action_force_goto_user(){do_shutter(1);location.href=path(0)}
function action_delete_generic(a,b){try{var c={currenttype:b};c[b+"id"]=firstelement(a);rvar.create("deletesomething","delete_"+b,c,function(a,b){cleaner(b[b.currenttype+"id"],b.currenttype);la["info_"+b.currenttype+"_deleted"]&&do_info(la["info_"+b.currenttype+"_deleted"])});ask(la["ask"+b+"del"],"rvar.deletesomething.sendreq()")}catch(d){msg("[action_delete_generic]:"+d),errnum=1}}
function action_delete_tag(a){try{rvar.create("deltag","delete_tag",{wordid:a[0],tagid:a[1]},function(a,b){cleaner(b.wordid+"_"+b.tagid,"tag")}),ask(la.asktagdel,"rvar.deltag.sendreq()")}catch(b){msg("[action_removefrom_tag]:"+b),errnum=1}}
action_rename_generic=action_edit_generic=function(a,b,c,d,e){a||debug.warning("id is not defined in action_edit_generic");b||debug.warning("type is not defined in action_edit_generic");hide_dropdown();if(!d){if(e==null)e=$$("."+b+"_"+firstelement(a))[0].innerHTML;d='<input id="input_edit" class="close_edit input_'+b+'" onkeyup="input_keyup(['+a+"], '"+b+"', 'edit', event)\" onkeydown=\"input_keydown(["+a+"], '"+b+"', 'edit', event)\" onblur=\"close_action('edit','"+b+'\',200)" type="text" name="new'+
b+'" value="'+e+'"/>'}Object.isElement(c)||debug.warning("where is not defined as an Element in action_edit_generic");Element.hide(c).insert({before:d});$$("#input_edit")[0].focus()};function action_edit_kword(a,b,c){a||debug.warning("id is not defined in action_edit_kword");b||debug.warning("type is not defined in action_edit_kword");var d=$$("."+b+"_v"+a[0]+"_p"+a[1]+"_f"+a[2])[0].innerHTML;action_edit_generic(a,b,c,!1,d)}
function action_edit_wordclass(a,b,c){for(var d=$$(".wordclass_"+firstelement(a))[0].innerHTML,e='<span class="close_edit"><select id="input_edit" onkeyup="input_keyup(['+a+"], 'wordclass', 'edit', event)\" onkeydown=\"input_keydown(["+a+"], 'wordclass', 'edit', event)\" name=\"newwordclass\" size=1 onblur=\"close_action('edit','"+b+'\',200)" onchange="send_input(['+a+"], 'wordclass','edit',13)\">",f=0;f<6;f++)e+="<option value="+f+" ",la.classname[f]==d&&(e+="selected"),e+=">"+la.classname[f]+"</option>";
e+="</select></span>";action_edit_generic(a,b,c,e)}
function action_edit_group(a,b,c){a||debug.warning("id is not defined in action_edit_group");b||debug.warning("type is not defined in action_edit_group");var d=$($$("."+b+"_"+firstelement(a))[0]).innerHTML,e='<span class="close_edit"><select id="input_edit" name="newgroup" size=1 onkeyup="input_keyup(\''+a+"', 'group', 'edit', event)\" onkeydown=\"input_keydown('"+a+"', 'group', 'edit', event)\" onblur=\"close_action('edit','"+b+"',200)\" onchange=\"send_input('"+a+"','group','edit',13)\">";d!=la.a_ar&&
d!=la.a_af&&(e+='<option value="'+d+'" selected>'+d+"</option>");d==la.a_ar&&(e+='<option value="ar">'+la.a_ar+"</option>");e+='<option value="af">'+la.a_af+"</option>";d!=1&&(e+='<option value="1">1</option>');e+="</select></span>";action_edit_generic(a,b,c,e)}
function action_speededit_wordclass(a,b,c){a||debug.warning("id is not defined in action_speededit_wordclass");b||debug.warning("type is not defined in action_speededit_wordclass");hide_dropdown();req("edit_word",{wordid:firstelement(a),newwordclass:c},after_send,{id:a,action:"edit",type:"wordclass",key:13})}
function action_add_generic(a,b,c){a||debug.warning("id is not defined in action_add_generic");b||debug.warning("type is not defined in action_add_generic");c||debug.warning("where is not defined in action_add_generic");hide_dropdown();c=="popup"?(c=new formparam("new"+b),c.addinput("new"+b,"name","",0),rvar.create("addsomething","create_"+b,{registerid:here.registerid},after_send,{action:"add",id:a,type:b}),request_form("addsomething",c)):(input='<input class="close_add" id="input_add" onkeyup="input_keyup(\''+
a+"', '"+b+"', 'add', event)\" onkeydown=\"input_keydown('"+a+"', '"+b+"', 'add', event)\" onblur=\"close_action('add','"+b+'\',200)" type="text" name="new'+b+'"></input>',Element.hide(c).insert({before:input}),$$("#input_add")[0].focus())}
function action_more_group(a,b,c){a||debug.warning("id is not defined in action_more_group");c||(c="++");req("edit_register",{registerid:a,newgroupcount:c},function(a,b){var c={location:"php/list.php","function":"list_group",json:1,parameters:Object.toJSON([b.registerid])};req("get_function",c,function(a){var b=$("group_content");if(b)b.insert({after:a.output}),eventloader(b.up()),b.remove(),refresh_subcount("group");else throw"HTML Element with id group_content not found.";})})}
function action_less_group(a,b){action_more_group(a,b,"--")}function action_show_generic(a,b){update_here({page:"show"});action_goto_generic(a,b)}function action_verb_generic(a,b){update_here({page:"verb"});action_goto_generic(a,b)}
function action_query_generic(a,b){a||debug.warning("id is not defined in action_query_generic");b||debug.warning("type is not defined in action_query_generic");do_shutter(1);if(here.page=="show"||here.page=="add")a="wordform";var c=formfield2id(a,"wordid[]");if(c===!1){if(c={allmarked:1},c[b+"id"]=firstelement(a),b=="register")here.registerid=a}else if(c===null)return!1;else c=$("check_allmarked").checked?{allmarked:1}:{"wordid[]":c};rvar.create("cract","create_active",here,function(a){document.location.href=
path(2,{queryid:a.savedid})});rvar.cract.sendreq(c)}function action_addword_generic(a,b){a||debug.warning("id is not defined in action_addword_generic");b||debug.warning("type is not defined in action_addword_generic");var c={keyoption:"add"};c[b+"id"]=a;location.href=path(c)}function action_export_generic(){location.href=path({keyoption:"export"})}function input_keydown_13_generic(a,b,c){send_input(a,b,c,13)}function input_keydown_9_generic(a,b,c){send_input(a,b,c,9)}
function input_keydown_27_generic(a,b,c){close_input_generic(a,b,c,27)}function input_keydown_16_generic(){local.current.keymodshift=!0}function input_keyup_16_generic(){local.current.keymodshift=!1}function send_edit_generic(a,b,c){try{var d=$("input_edit");if(d){var e={};e[b+"id"]=a;e["new"+b]=d.value;req("edit_"+b,e,after_send,{id:a,type:b,key:c,action:"edit"})}}catch(f){msg("[send_edit_generic]:"+f),errnum=1}}
send_edit_wordfore=send_edit_wordfirst=send_edit_group=send_edit_sentence=send_edit_wordclass=function(a,b,c){var d=$("input_edit");if(d){if(b=="wordfirst"||b=="wordfore")if(validstr(d.value))return do_info(la.err_invalidsyntax),!1;else close_info();var e={wordid:firstelement(a)};e["new"+b]=d.value;req("edit_word",e,after_send,{id:a,type:b,action:"edit",key:c})}};
function send_edit_kword(a,b,c){a||debug.warning("id is not defined in send_edit_generic");try{var d=$("input_edit");d&&req("add_verb",{wordid:a[0],personid:a[1],formid:a[2],newkword:d.value},after_send,{id:a,type:b,action:"edit",key:c})}catch(e){msg("[send_edit_kword]:"+e),errnum=1}}
function send_edit_grouplock(a,b,c){a||debug.warning("id is not defined in send_edit_grouplock");var d=$("input_edit");if(d){for(var e=parseFloat(a)-2,f=[],g=0;g<e;g++)f.push(null);f[e]=d.value;req("edit_register",{registerid:here.registerid,"newgrouplock[]":f},after_send,{id:a,type:b,action:"edit",key:c})}}
function after_send_edit_13_generic(a,b,c,d,e){try{e==null&&(e=b["new"+d]),$$("."+d+"_"+c).each(function(a){a.update(e)}),close_action("edit",d),clear_data(d)}catch(f){msg("[after_send_edit_13_generic]:"+f),errnum=1}}function after_send_edit_13_wordclass(a,b,c,d){after_send_edit_13_generic(null,null,c,d,la.classname[b.newwordclass])}function after_send_edit_13_register(a,b,c,d){after_send_edit_13_generic(null,null,c,d,a.registername)}
function after_send_edit_13_kword(a,b,c,d){try{$$("."+d+"_v"+c[0]+"_p"+c[1]+"_f"+c[2]).each(function(b){b.update(a.newkword)}),close_action("edit",d),clear_data(d)}catch(e){msg("[end_edit_after_13_kword]:"+e),errnum=1}}
function after_send_edit_9_generic(a,b,c,d,e){try{if(after_send(a,b,{key:"13",action:"edit",id:c,type:d}),e||(e=$$(".tab_"+d+"_"+c)),e.length!=0){var f=$$('[class^="tab_"]'),g=local.current.keymodshift?-1:1;if(nextobj=f[f.indexOf(e[0])+g])nextobj.ondblclick()}}catch(h){msg("[after_send_edit_9_generic]:"+h),errnum=1}}function after_send_edit_9_kword(a,b,c,d){after_send_edit_9_generic(a,b,c,d,$$(".tab_"+d+"_v"+c[0]+"_p"+c[1]+"_f"+c[2]))}
function after_send_edit_13_group(a,b,c,d){after_send_edit_13_generic(a,b,c,d,typeof b.newgroup!="integer"?la["a_"+b.newgroup]:b.newgroup)}function after_send_edit_13_grouplock(a,b,c,d){after_send_edit_13_generic(a,b,c,d,b["newgrouplock[]"][parseFloat(c)-2])}function send_add_generic(a,b,c){try{var d=$("input_add");if(d){var e={};e.registerid=here.registerid;e["new"+b]=d.value;req("create_"+b,e,after_send,{id:a,type:b,action:"add",key:c})}}catch(f){msg("[send_edit_generic]:"+f),errnum=1}}
function send_add_tag(a,b){try{var c=$("input_add");if(c){var d={};d.registerid=here.registerid;d["wordid[]"]=a;d.newtag=c.value;req("add_tag",d,after_send,{id:a,type:b,action:"add",key:13})}}catch(e){msg("[send_edit_generic]:"+e),errnum=1}}
function after_send_add_13_tag(a,b,c){try{close_action("add","tag");for(var d=a.id.length-1;d>=0;d--)$("tag_span_"+c+"_"+a.id[d])&&(a.id.splice(d,1),a.name.splice(d,1));if(a.id.length==0)return!1;var e=get_function_writeone("tag");e.json=1;e.parameters=Object.toJSON([c,a.id,a.name]);req("get_function",e,function(a){appender(a.output,"tag",$("tag_"+c),"top")})}catch(f){msg("[after_send_add_13_tag]:"+f),errnum=1}}
function after_send_add_13_generic(a,b,c,d,e){try{var f=get_function_writeone(d);e==null?(f.parameters=Object.toJSON([{id:a.newid,name:a.newname,count:a.count}]),f.json=1):f["parameters[]"]=e;req("get_function",f,function(a,b,c){appender(a.output,c[0],c[1],c[2])},[d,$$("."+d+"_list")[0],"bottom"]);close_action("add",d)}catch(g){msg("[after_send_add_13_generic]:"+g),errnum=1}}
function after_send_add_0_generic(a,b,c,d,e){try{after_send_add_13_generic(a,b,c,d,e),close_popup()}catch(f){msg("[after_send_add_0_generic]:"+f),errnum=1}}function after_send_add_0_person(a,b,c,d){b=get_function_writeone(d);b.parameters=Object.toJSON([{id:a.newid,name:a.newname,count:a.count}]);b.json=1;req("get_function",b,function(a){appender(a.output,d,$$("."+d+"_list")[0],"bottom")});close_popup()}function after_send_add_0_form(a,b,c,d){after_send_add_0_person(a,b,c,d)}
function link_all_generic(a,b){return'<li class="menulink link" onclick="do_action(null,\''+b+"','goto')\">"+la.all+"</li>"}function link_show_generic(a,b){return'<li class="menulink link" onclick="do_action(\''+a+"','"+b+"','goto')\">"+la.show+"</li>"}function link_show_wordclass(a){return link_show_generic(a[1],"wordclass")}function link_show_group(a){return link_show_generic(a[1],"group")}
function link_options_generic(a,b){return'<li class="menulink link" onclick="update_here({'+b+"id:'"+a+"'}); do_action('edit','keyoption','goto')\">"+la.options+"</li>"}function link_settings_user(){return"<li class=\"menulink link\" onclick=\"do_action('settings','keyoption','force_goto')\">"+la.settings+"</li>"}function link_logout_generic(){return"<li class=\"menulink link\" onclick=\"do_action('logout','keyoption','force_goto')\">"+la.logout+"</li>"}
function link_import_generic(){return"<li class=\"menulink link\" onclick=\"do_action('import','keyoption','goto')\">"+la["import"]+"</li>"}function link_addword_generic(){return'<li class="link menulink link_addword" onclick="do_action(false,false,\'addword\')">'+la.addword+"</li>"}function link_goto_generic(a,b,c){return'<li class="menulink link" onclick="do_action(\''+a+"','"+b+"','goto')\">"+c+"</li>"}
function link_taglist_tag(){return"<li class=\"menulink link\" onclick=\"do_action('taglist','keyoption','goto')\">"+la.taglist+"</li>"}function link_without_generic(a,b){return'<li class="menulink link" onclick="do_action(\''+b+"','without','goto')\">"+la["without"+b]+"</li>"}function link_verbtable_word(a){return'<li class="menulink link" onclick="do_action(\''+a+"','verb','goto')\">"+la.verb+"</li>"}
function link_list_edit_wordclass(a){for(var b="",c=0;c<6;c++)b+="<li class='menulink link' onclick='action_speededit_wordclass(["+a+'],"wordclass",'+c+")'>"+la.classname[c]+"</li>";return b}function link_help(a,b,c){if(you.hints==1||b==1)return'<span class="link helplink h_'+a+'" onmouseover="help_load(\''+a+'\')" onclick="help_toggle();">'+(c||"")+"</span>"}
function close_input_generic(a,b){var c=$$(".close_"+b)[0];if(!c)return!1;a!=null?local.current.close_input_delay=setTimeout(function(){close_input_generic(null,b)},a):(where=c.next(),Element.show(where).previous().addClassName("input_closed").remove(),clearTimeout(local.current.close_input_delay))}function close_edit_generic(a){close_input_generic(a,"edit")}function close_add_generic(a){close_input_generic(a,"add")}
function clear_data(a){if(a===void 0)delete local.data,local.data={};else{if(typeof a=="string")a=[a];else if(typeof a!="object")throw'[clear_data]: "type" must be string or array!';for(var b=0;b<a.length;b++)delete local.data[a[b]]}}function update_information(){close_info();var a=switcher("update_information",here.page);if(a)window[a]()}
function update_page(a){update_here({page:a});here.page!="search"&&update_here({searchid:null});update_hash();update_navigator();update_information();var b=switcher("update",a);if(b)window[b]();$("content").className="page_"+a}function update_navigator(){var a={location:"php/menu.php","function":"navigator"};a.parameters="["+Object.toJSON(here)+"]";a.json=1;req("get_function",a,function(a){eventloader($("headerpath").update(a.output))})}
function request_form(a,b){var c=0,d="<form id='askform' action='#' onsubmit='if(checkrform()) { return rvar."+a+'.sendreq($("askform").serialize(true)); } else { return false; }\'>';d+='<span class="titel reqformtitel">'+la[b.title]+":</span>";b.error&&(d+='<div class="reqformerr">'+la[b.error]+"</div>");d+='<ul class="inputlist">';try{for(var e in b.input){var f=b.input[e],g=f.id?f.id:f.name;d+="<li><label for='"+g+"'>"+la[f.label]+":</label><input type='"+(f.type?f.type:"text")+"' name='"+f.name+
"' id='"+g+"' value='"+f.value+"' "+(f.needed==1?' class="form_need" ':"")+"></li>"}}catch(h){msg("[request_form_0]:"+h),c=1}try{for(var j in b.select){var k=b.select[j],g=k.id?k.id:name;d+="<li><label for='"+g+"'>"+la[k.label]+":</label><select name='"+k.name+"' size='1' id='"+g+"'>";for(var l in k.option)d+="<option value='"+l+"' "+(l==k.selected?"selected='selected'":"")+">"+k.option[l]+"</option>";d+="</select></li>"}}catch(m){msg("[request_form_1]:"+m),c=2}d+='<ul class="inputlist">';d+="<input type='submit' value='"+
la[b.submittext]+"'>";d+="<input type='button' value='"+la[b.canceltext]+"' onclick='close_popup()'/>";d+="</form>";c==0&&($("popup").update(d),do_popup(),$("askform")[g].focus())}function checkrform(){try{for(var a=!0,b=0,c=$$("input.form_need");input=c[b];){if(input.value==""){input.focus();a=!1;break}b++}return a}catch(d){return msg("[checkrform]:"+d),!1}}function do_shutter(a){$("shutter").clonePosition($("content"),{setTop:!1}).show();$("loadbar")[a?"show":"hide"]()}
function close_shutter(){$("shutter").hide()}function do_info(a){$("info").show().down("span").update(a)}function close_info(a){(!a||$("info").down("span").innerHTML==a)&&$("info").hide().down("span").update()}
function do_popup(){var a=$("popup");do_shutter();a.removeClassName("hide");var b=document.body.clientHeight,c=document.body.clientWidth,d=a.clientHeight,e=a.clientWidth,f=Math.round(b*0.8);d>f&&(d=f,a.setStyle({height:f+"px"}));a.setStyle({top:Math.round(b/2-d/2)+"px",left:Math.round(c/2-e/2)+"px"})}function close_popup(){try{close_shutter();var a=$("popup");a.addClassName("hide");a.update()}catch(b){}}
function load_dropdown_mouse(a){hold_dropdown();var b=$("dropdown");b.update(a);position_dropdown();eventloader(b);b.show()}function load_dropdown(a,b){hold_dropdown();if(!b)return!1;var c=getposition($(a)),d=c[0],c=c[1]+$(a).offsetHeight+2,e=$("dropdown");e.update(b);e.setStyle({top:c+"px",left:d+"px"});eventloader(e);e.show()}
function position_dropdown(){var a=$("dropdown"),b=document.viewport.getDimensions(),c=a.getDimensions(),d=0,d=b.height>=local.mouseY+c.height?local.mouseY:0<local.mouseY-c.height?local.mouseY-c.height:5;a.setStyle({top:d+"px",left:(b.width<local.mouseX+c.width?local.mouseX-c.width:local.mouseX)+"px"})}function hide_dropdown(a){if(!$("dropdown"))return!1;a==null&&(a=400);local.close_dropdown_timer=window.setTimeout("$('dropdown').hide()",a)}
function hold_dropdown(){window.clearTimeout(local.close_dropdown_timer)}function showstatus(a){var b=$("statusbar");if(b.innerHTML!=""){position=getposition($(a));var c=position[0],a=position[1]+$(a).offsetHeight+2;b.setStyle({top:a+"px",left:c+"px"});b.show()}}function hidestatus(a){a==null&&(a=200);local.close_status_timer=window.setTimeout("$('statusbar').hide()",a)}function holdstatus(){window.clearTimeout(local.close_status_timer)}
function multicheck(a){local.mouseisdown==1&&checkthisbox(a)};local.as={};local.asgot={};local.aselect=-1;local.types={register:la.register,group:la.group,tag:la.tag,save:la.savepoint,word:la.word,wordclass:la.wordclass,without:la.without,verb:la.sverb,form:la.form,person:la.person,search:la.search};function highlight_match(a,b,c){var d=b.search(RegExp(a,"i"));return d!=-1?b.substr(0,d)+'<span class="'+c+'">'+b.substr(d,a.length)+"</span>"+b.substr(d+a.length):b}function hide_autosearch(){$("autosearcher").hide()}
function show_search(){$("searchclick").hide();var a=$("searchform");a.setStyle({display:"inline-block"});a.searchtext.focus()}function hide_search(a){if(!$("searchform"))return!1;a==null&&(a=400);local.close_search_timer=window.setTimeout("$('searchform').hide(); $('searchclick').setStyle({ display:'inline-block'}); hide_autosearch();",a)}function hold_search(){window.clearTimeout(local.close_search_timer)}function reset_search(){hide_autosearch();local.aselect=-1;$("searchtext").value=""}
function auto_hl_down(){autochoose(1);auto_highlight(local.aselect)}function auto_hl_up(){autochoose(-1);auto_highlight(local.aselect)}function autochoose(a){if($("autolist")){local.aselect+=a;a=$("autolist").childNodes;if(local.aselect<-1)local.aselect=-1;if(local.aselect>a.length-1)local.aselect=a.length-1}}
function auto_highlight(a){if($("autolist"))for(var b=$("autolist").childNodes,c=0;c<b.length;c++)c==a||b[c]==a?(Element.writeAttribute(b[c],"class","list_marked"),$("searchtext").value=b[c].title):Element.writeAttribute(b[c],"class","list_none")}
function search(){try{if(!local.data.register.count)return!1;update_here({searchid:null});var a=$("searchtext").value;$("searchform");if(a!=""){var b=0;if(a.indexOf(local.types.search+":")!=0){var c=a.split(":")[0].strip(),c=Object.keys(local.types)[Object.values(local.types).indexOf(c)];c!==void 0&&(a=a.substr(a.indexOf(":")+1).strip());var d=a.split("/")[0].strip(),e=local.data.register.name.indexOf(d);e!=-1&&(update_here({registerid:local.data.register.id[e]}),a=a.substr(a.indexOf("/")+1).strip());
if(a&&(a!=d||e==-1)){c=="group"&&isFinite(parseInt(a))&&(b=1,do_action(parseInt(a),"group","goto"),reset_search());var f=local.as[local.current.subtext][c];if(f&&f.count)for(var g=c=="word"?[f.wordfirst,f.wordfore,f.sentence]:c=="verb"?[f.kword]:[f.name],d=0;d<g.length;d++){var h,e=0;do h=g[d].indexOf(a,e),e=h+1;while(f.registerid[h]!=here.registerid&&h!=-1);if(h!=-1){b=1;do_action(c=="verb"?f.wordid[h]:f.id[h],c,"goto");reset_search();break}}}else b=1,do_action(null,null,"goto"),reset_search()}b==
0&&(do_action(a,"search","goto"),reset_search())}return!1}catch(j){msg("[search]:"+j+" - st = "+a)}}function block_keydown(a){if(get_key(a)==9)return!1;return!0}function action_search(a){try{var b=!0,c=get_key(a);c==27?(reset_search(),hide_search(0)):c==40||c==9?(b=!1,auto_hl_down()):c==38?(b=!1,auto_hl_up()):c==13?search():(update_here({searchid:$("searchtext").value}),get_searchresult());return b}catch(d){msg("[action_search]:"+d+"")}}
function get_searchresult(){try{local.data.register||req("get_register",[],function(a){local.data.register=a});var a=here.searchid;if(a.length<3)return proceed_searchresult(),0;local.current.subtext=a.substr(0,3);var b=local.current.subtext;local.as[b]||(local.as[b]={});local.asgot[b]?proceed_searchresult():(local.asgot[b]=!0,local.as[b].type={count:11,name:Object.values(local.types),id:Object.keys(local.types)},local.as[b].group={count:2,registerid:fill_array(here.registerid,2),name:[la.af,la.ar],
id:["af","ar"]},local.as[b].without={count:2,registerid:fill_array(here.registerid,2),name:[la.tag,la.savepoint],id:["tag","save"]},local.as[b].wordclass={count:6,registerid:fill_array(here.registerid,6),name:la.classname,id:[0,1,2,3,4,5,6]},req("search",{searchtext:b},function(a,b){Object.extend(local.as[b.searchtext],a);proceed_searchresult()}))}catch(c){msg("[get_searchresult]:"+c+"")}}
function proceed_searchresult(){try{var a=here.searchid,b=local.current.subtext,c=[[],[],[],[],[],[],[],[],[],[],[],[]],d;for(d in local.as[b]){var e=local.as[b][d];if(e.count)for(var f=d=="word"?["wordfirst","wordfore","sentence"]:d=="verb"?["kword"]:["name"],g=0;g<f.length;g++)for(var h=0;h<e[f[g]].length;h++){var j=0;d!="register"&&e.registerid&&e.registerid[h]!=here.registerid&&(j=5);try{var k=e[f[g]][h].toLowerCase();if(k.match("^"+a.toLowerCase()+"$"))c[0].push([d,f[g],h]);else if(k.match("^"+
a.toLowerCase()+" "))c[1+j].push([d,f[g],h]);else if(k.match(" "+a.toLowerCase()+" ")||k.match(" "+a.toLowerCase()+"$"))c[2+j].push([d,f[g],h]);else if(k.match("^"+a.toLowerCase()))c[3+j].push([d,f[g],h]);else if(k.match(a.toLowerCase()))c[4+j].push([d,f[g],h]);else{var l=a.toLowerCase().split("").join(".?");k.match(l)&&c[5+j].push([d,f[g],h])}}catch(m){msg("[proceed_searchresult_1]:"+m+" - st: "+a.inspect()+" | probe: "+k.inspect()),error={s:f,sres:c}}}}local.current.searchresult=[];for(d=0;d<c.length;d++)local.current.searchresult=
local.current.searchresult.concat(c[d]);update_searchresult()}catch(o){msg("[proceed_searchresult]:"+o+"")}}
function update_searchresult(){try{var a=here.searchid,b=local.current.subtext,c=local.current.searchresult;here.page=="show"&&update_here({page:"search"});var d=switcher("update_searchresult",here.page);if(d)window[d]();if(c.length==0)return hide_autosearch(),0;if($("searchclick").visible())return hide_autosearch(),0;for(var d=[],e=0;e<c.length;e++){var f="",g="",h="",j=c[e];if(!(here.page=="search"&&j[0]=="word")){j[0]!="type"&&(g+=local.types[j[0]]+": ");if(j[0]!="register"&&local.as[b][j[0]].registerid){var k=
local.as[b][j[0]].registerid[j[2]];here.registerid!=k&&(g+=get_name("register",k)+"/ ")}f+=highlight_match(a,local.as[b][j[0]][j[1]][j[2]],"markedsearch");j[0]=="type"&&(h+=": ");var l='<li onmouseover="auto_highlight(this)" title="'+g+local.as[b][j[0]][j[1]][j[2]]+h+'">';l+=g+f+h;l+="</li>";d.push(l)}}f='<ul id="autolist" onclick="javascript: search()">';f+=d.join("")+"</ul>";position=getposition($("searchtext"));var m=position[0],o=position[1]+$("searchtext").offsetHeight,n=$("autosearcher");n&&
(n.update(f),n.setStyle({top:o+"px",left:m+"px",width:$("searchtext").offsetWidth-10+"px"}),n.show())}catch(p){msg("[update_searchresult]:"+p+""),local.error={s:j}}};local.help={};local.help.loaded={};local.help.title={};local.help.value={};document.observe("dom:loaded",function(){help_toggle();req("get_help",{language:you.language,gettitle:1},help_content);$$("a.wordedit").each(function(a){a.onmouseover=function(){help_load("wordedit")}})});
function help_load(a){if(local.help.opened!=a)local.help.opened=a,local.help.title[a]?help_show({titletext:local.help.title[a],valuetext:local.help.value[a]},a):req("get_help",{title:a,language:you.language},function(a,c,d){help_show(a,d)},a)}function help_content(a){for(var b="",c=0;c<a.count;c++)b+='<span class="link" onclick="help_load(\''+a.title[c]+"')\">"+a.titletext[c]+"</span><br>";help_show({titletext:la.content,valuetext:[b]},"content")}
function help_show(a,b){if(!local.help.title[b])local.help.title[b]=a.titletext,local.help.value[b]=a.valuetext;$("helper_head_span").innerHTML=a.titletext;var c=$("helper_body"),d=a.valuetext[0].replace(/\n/g,"<br>");b!="content"&&(d+='<br><br><span class="link" onclick="help_load(\'content\')">'+la.content+"</span><br>");c.update(d);$("helper").show()}
function help_toggle(){var a=$("helper_body");a.hasClassName("hide")?(a.removeClassName("hide"),$("helper").setStyle({opacity:1})):(a.addClassName("hide"),$("helper").setStyle({opacity:0.5}))}function help_close(){$("helper_body").removeClassName("hide");local.help.opened=null;$("helper").hide()};function ableall(a,b){for(var c=0,d=$$("input.im_"+a);d[c];)d[c][b==1?"enable":"disable"](),c++;c=0;for(d=$$("fieldset.im_"+a);d[c];)d[c][b==1?"show":"hide"](),c++};function initializer_add(){initializer_show()}function initializer_show(){checkscroll()}function initializer_search(){get_searchresult()}function initializer_overview(){local.wordlist_complete=1;update_overview()}
function eventloader_overview(a){eventloader_show(a);a.select('[class~="highlighted_element"]').each(function(a){a.removeClassName("highlighted_element")});for(var b=["group","tag","save","wordclass","without"],c=0;c<b.length;c++)a.select("."+b[c]+"_"+here[b[c]+"id"]).each(function(a){a.addClassName("highlighted_element")})}
eventloader_search=eventloader_add=eventloader_show=function(a){a.select(".event_hidelast_in").each(function(a){a.onmouseover=function(){this.lastChild.lastChild.removeClassName("hidden")};a.onmouseout=function(){this.lastChild.lastChild.addClassName("hidden")}});a.select('[id^="tab_"]').each(function(a){a.onclick=function(){tab_switch(this.id.slice(4))}});a.select('tr[id^="wordlist_tr"]').each(function(a){a.onmouseover=function(){this.lastChild.lastChild.removeClassName("hidden");highlighthover(this,
!0)};a.onmouseout=function(){this.lastChild.lastChild.addClassName("hidden");highlighthover(this,!1)}});a.select(".dropdown_giver").each(function(a){a.onmouseover=hold_dropdown;a.onmouseout=function(){hide_dropdown()}})};function appendit(a,b){try{var b=b||0,c=$("wordlist").down("tbody");b==0?c.insert({bottom:a}):b==1&&c.insert({top:a});eventloader(c);hidecolumns();close_shutter();a?checkscroll():local.wordlist_complete=1}catch(d){msg("Error[appendit]: "+d)}}
function appendwords(a,b,c,d){try{var e=Object.clone(a),a={};e.fromlim=b;e.tolim=c;a.location="php/wordtable.php";a["function"]="wordform";a.json=1;if(!a.parameters){var f=$("check_allmarked");a.parameters=f?Object.toJSON([e,f.checked?1:0,here.registerid?0:1]):Object.toJSON([e,0,here.registerid?0:1])}req("get_function",a,function(a,b,c){appendit(a.output,c)},d)}catch(g){msg("Error[appendwords]: "+g)}}
function highlighthover(a,b){Element.hasClassName(a,"list_marked")||(b?a.addClassName("list_hover").removeClassName("list_none"):a.addClassName("list_none").removeClassName("list_hover"))}function checkthisbox(a){if(a=$("check_"+a))a.checked=!a.checked,checkbox_updatehighlight(a)}
function checkbox_updatehighlight(a){var b=$("wordlist_tr_"+a.value);b&&(a.checked?b.addClassName("list_marked").removeClassName("list_none").removeClassName("list_hover"):b.addClassName("list_none").removeClassName("list_marked"))}function checkbox_checkall(a){$$('input[id^="check_"]').each(function(b){b.checked=a;checkbox_updatehighlight(b)})}function displaycolumn(a,b){hide_dropdown(0);$$("[id^="+b+"_]").each(function(b){a?b.show():b.hide()})}
function hidecolumns(){$$('th[id$="_head"]').each(function(a){a.getStyle("display")=="none"&&(a=a.identify().slice(0,-5),displaycolumn(0,a))})}
function checkscroll(){if(here.page!="show"&&here.page!="add")return local.wordlist_complete=1,!1;var a=$("content");a.scrollHeight-a.scrollTop-a.clientHeight<=300&&document.body.scrollHeight-document.body.scrollTop-document.body.clientHeight<=300?(fromlim=parseFloat($("wordlist").down("tbody").childNodes.length),fromlim==0&&here.page=="show"?do_info(la.err_102):close_info(la.err_102),$$(".with_wordlist").each(function(a){fromlim?a.show():a.hide()}),$$(".-with_wordlist").each(function(a){fromlim?
a.hide():a.show()}),displaycolumn(here.registerid?0:1,"register"),fromlim==0&&do_shutter(1),appendwords(here,fromlim,25,0)):window.setTimeout("checkscroll()",1E3)}link_goto_generic_search=link_goto_generic_overview=link_goto_generic_show=function(a,b,c){return'<li class="link menulink" onclick="do_action(\''+a+"','"+b+"','goto')\">"+c+"</li>"};
link_hide_group=link_hide_tag=link_hide_wordclass=link_hide_word=function(a,b){return'<li class="menulink link columnbutton" onclick="javascript: displaycolumn(0,\''+b+"')\">"+la.hide+"</li>"};action_goto_generic_show=action_goto_generic_overview=action_goto_generic_search=function(a,b){do_shutter(1);b!="word"&&update_here({wordid:null});if(b!=null){var c={};c[b+"id"]=a;update_here(c)}here.searchid!=null?tab_switch("search",1):b=="register"?tab_switch("overview",1):tab_switch("show",1)};
action_goto_search_show=action_goto_search_overview=action_goto_search_search=function(a){do_shutter(1);clear_here("wordid");update_here({searchid:a});update_here({searchtext:"like: "+a});here.searchid==null?tab_switch("show",1):tab_switch("search",1)};
function update_show(){close_info();$$('tr[id^="wordlist_tr"]').each(function(a){a.remove()});if(here.page=="add"){var a=(new Date).getTime()/1E3,a=Math.floor(a);here.timerange=[a-10800,a,"DESC"]}else here.timerange=null;local.wordlist_complete==1&&here.page!="search"?(local.wordlist_complete=0,checkscroll()):close_shutter()}
function update_overview(){try{if(local.cached_overview)eventloader(),refresh_subcount(),close_shutter();else{local.cached_overview=1;do_shutter(1);var a={location:"php/tab.php","function":"overview",json:1,parameters:Object.toJSON([here.registerid])};req("get_function",a,function(a){var b=$("content_tab_overview");if(b)b.update(a.output),eventloader(b),refresh_subcount(),close_shutter();else throw"could not find HTML Element with id tab_overview_content in update_overview";})}}catch(b){msg("Error[update_overview]: "+
b)}}function update_search(){update_here({searchtext:"like: "+here.searchid});get_searchresult();close_shutter()}
function refresh_subcount(a){itypes=a?a:["group","tag","wordclass","save","without"];a!==void 0&&(itypes=typeof a=="string"?[a]:a);for(var b=!0,a=0;a<itypes.length;a++)if(here[itypes[a]+"id"]!=null){b=!1;break}if(b)return $$('[class*="_subcount_"]').each(function(a){a.hide()}),!1;for(a=0;a<itypes.length;a++){$$('[class*="'+itypes[a]+'_subcount_"]').each(function(a){a.show().update("0/")});b=Object.clone(here);b[itypes[a]+"id"]=null;b.type=itypes[a];b.gettags=0;if(itypes[a]==="without"){var c=Object.clone(b);
c.tagid=null;c.withoutid="tag";c.count="1";req("get_word",c,update_subcount);b=Object.clone(b);b.saveid=null;b.withoutid="save";b.count="1"}else b.count=itypes[a];req("get_word",b,update_subcount)}}function update_subcount(a,b){for(var c=b.type,d=0;d<a.count;d++){var e=c=="without"?b.withoutid:a[c+"id"][d],f=$$('[class~="'+c+"_fullcount_"+e+'"]')[0];f&&a.wordcount[d]==f.innerHTML?update_subcount_of(c,e):update_subcount_of(c,e,a.wordcount[d])}}
function update_subcount_of(a,b,c){$$('[class~="'+a+"_subcount_"+b+'"]').each(function(a){c===null||c===void 0?a.hide():a.update(c+"/")})}function update_information_show(){here.wordid!=null&&do_info(la.info_singleword+" <span class=\"link\" onclick=\"do_action(null,'word','goto')\">"+la.showall+"</span>")}function update_information_search(){here.registerid!=null&&do_info(la.info_singlesearch+" <span class=\"link\" onclick=\"do_action(null,'register','goto')\">"+la.searchall+"</span>")}
function tab_switch(a,b){if(here.page==a&&!b)return!1;do_shutter(1);var c=$$(".tab_active")[0],d=$("tab_"+a);if(!$("content"))throw"Warning [tab_switch]: could not switch tabs: $('content') is not an element";c&&c.removeClassName("tab_active").addClassName("tab_inactive");d&&d.removeClassName("tab_inactive").addClassName("tab_active");$$('[class*="intab_"]').each(function(a){a.hide()});$$('[class~="intab_'+a+'"]').each(function(a){a.show()});update_page(a)}
function load_data_tag_word(a,b,c){try{var d=fill(c,a),e=Object.clone(here);e["wordid[]"]=formfield2id("wordform","wordid[]");req("get_tag",e,function(a,b,c){local.data.tag_word=a;window[d](c)},b)}catch(f){msg("[load_data_tag_word]:"+f)}}function fill_select_group(a){var b='<option value="1">'+la.group+" 1</option>";b+='<option value="af">'+la.af+"</option>";a&&a.insert({after:b}).remove()}
function fill_select_generic(a,b){if(local.data[b].count==0)return msg(la["err_no"+b]),!1;var c,d="";for(c=0;c<local.data[b].count;c++)d+='<option value="'+local.data[b].id[c]+'"',here[b+"id"]==local.data[b].id[c]&&(d+=" selected"),d+=">"+local.data[b].name[c]+"</option>";a&&a.insert({after:d}).remove()}function fill_select_tag_word(a){if(local.data.tag_word.count==0)return msg(la.err_notag),!1;else fill_select_generic(a,"tag_word")}
function load_data_more_options(a,b,c){if(a=fill(c,a))window[a](b,c)}
function fill_list_more_options(a){var b="<li class=\"menulink link icon_text\" onclick=\"do_action('wordform','word','multi_delete')\" ><span class=\"icon iconx\"></span>"+la.deletewords+"</li>";b+="<li class=\"menulink link icon_text\" onclick=\"do_action('wordform','word','multi_move','popup')\"><span class=\"icon iconarrowright\"></span>"+la.movewords+"</li>";here.registerid!=null&&(b+="<hr>",b+="<li class=\"menulink link icon_text\" onclick=\"do_action('wordform','tag','multi_addto','popup')\"><span class=\"icon iconplus\"></span>"+la.addtag+
"</li>",b+="<li class=\"menulink link icon_text\" onclick=\"do_action('wordform','tag','multi_delete','popup')\"><span class=\"icon iconx\"></span>"+la.deletetag+"</li>",b+="<hr>",b+="<li class=\"menulink link icon_text\" onclick=\"javascript: do_action('wordform','save','add','popup')\"><span class=\"icon iconplus\"></span>"+la.newsave+"</li>",b+="<li class=\"menulink link icon_text\" onclick=\"do_action('wordform','save','multi_addto','popup')\"><span class=\"icon iconarrowright\"></span>"+la.inserttosave+
"</li>");here.saveid!=null&&(b+="<li class=\"menulink link icon_text\" onclick=\"do_action('wordform','save','multi_removefrom','popup')\"><span class=\"icon iconx\"></span>"+la.removefromsave+"</li>");put_list(b,a)}
function action_multi_move_word(){try{id=formfield2id("wordform","wordid[]");if(!id)return!1;var a=new formparam("moveto","move");a.addselect("movetogroup","group");a.select.movetogroup.addoption({"null":la.loading});rvar.create("moveto","edit_multiword",{"wordid[]":id},after_send,{id:id,action:"multi_move",type:"word",key:0});request_form("moveto",a);load_data("select",$("movetogroup").down(),"group")}catch(b){msg("[action_multi_move_word]:"+b)}}
function action_multi_delete_word(a){try{a=formfield2id("wordform","wordid[]");if(!a)return!1;rvar.create("delmarked","delete_word",{"wordid[]":a},after_send,{id:a,action:"multi_delete",type:"word",key:0});ask(la.askworddels,"rvar.delmarked.sendreq()")}catch(b){msg("[action_multi_delete_word]:"+b)}}
function action_multi_addto_tag(a){try{a=formfield2id("wordform","wordid[]");if(!a)return!1;var b=new formparam("addtag");b.addinput("newtag","name");rvar.create("addtag","add_tag",{registerid:here.registerid,"wordid[]":a},after_send,{id:a,action:"multi_addto",type:"tag",key:0});request_form("addtag",b)}catch(c){msg("[action_multi_addto_tag]:"+c)}}
function action_multi_delete_tag(a){try{a=formfield2id("wordform","wordid[]");if(!a)return!1;var b=new formparam("deletetag","delete");b.addselect("tagid","tag");b.select.tagid.addoption({"null":la.loading});rvar.create("deletetag","delete_tag",{"wordid[]":a},after_send,{id:a,action:"multi_delete",type:"tag",key:0});request_form("deletetag",b);load_data("select",$("tagid").down(),"tag_word")}catch(c){msg("[action_multi_delete_tag]:"+c)}}
function action_add_save(a){try{a=formfield2id("wordform","wordid[]");if(!a)return!1;var b=new formparam("newsave");b.addinput("newsave","name");rvar.create("addsave","create_save",{registerid:here.registerid,"wordid[]":a},after_send,{id:a,action:"add",type:"save",key:0});request_form("addsave",b)}catch(c){msg("[action_add_save]:"+c)}}
function action_multi_addto_save(a){try{a=formfield2id("wordform","wordid[]");if(!a)return!1;var b=new formparam("insertto","insert");b.addselect("newsaveid","savepoint");b.select.newsaveid.addoption({"null":la.loading});rvar.create("insertinto","add_tosave",{registerid:here.registerid,"wordid[]":a},after_send,{id:a,action:"multi_addto",type:"save",key:0});request_form("insertinto",b);load_data("select",$("newsaveid").down(),"save")}catch(c){msg("[action_multi_addto_save]:"+c)}}
function action_multi_removefrom_save(a){try{a=formfield2id("wordform","wordid[]");if(!a)return!1;rvar.create("remfsave","delete_fromsave",{saveid:here.saveid,registerid:here.registerid,"wordid[]":a},after_send,{id:a,action:"multi_removefrom",type:"save",key:0});ask(la.delwordfromsave,"rvar.remfsave.sendreq()")}catch(b){msg("[action_multi_addto_tag]:"+b)}}
function after_send_multi_move_0_word(a,b){close_popup();var c=b["wordid[]"];typeof c!="object"&&(c=[c]);for(var d=0;d<c.length;d++){var e=c[d];if(here.groupid!=null&&b.movetogroup!=here.groupid)$$('[id="wordlist_tr_'+e+'"]')[0].remove();else if(b.movetogroup!=0){var f=b.movetogroup=="af"||b.movetogroup=="ar"?la["a_"+b.movetogroup]:b.movetogroup;$$('[id="group_span_'+e+'"]')[0].update(f)}}c.length!=0&&do_info(c.length+" "+(c.length==1?la.info_word_moved:la.info_words_moved))}
function after_send_multi_delete_0_word(a,b){cleaner(b["wordid[]"],"word");a.count!=0&&do_info(a.count+" "+(a.count==1?la.info_word_deleted:la.info_words_deleted))}
function after_send_multi_addto_0_tag(a){try{close_popup();var b=get_function_writeone("tag");b.json=1;for(var c=0;c<a.countword;c++){for(var d=[],e=[],f=0;f<a.tagid.length;f++)$("tag_span_"+a.wordid[c]+"_"+a.tagid[f])||(d.push(a.tagid[f]),e.push(a.tags[f]));if(a.tagid.length==0)return!1;b.parameters=Object.toJSON([a.wordid[c],d,e]);req("get_function",b,function(a,b,c){appender(a.output,"tag",$("tag_"+c),"top")},a.wordid[c])}a.tagid.length!=0&&do_info(a.tagid.length+" "+(a.tagid.length==1?la.info_tag_added:
la.info_tags_added))}catch(g){msg("[after_send_multi_addto_0_tag]:"+g),errnum=1}}function after_send_multi_delete_0_tag(a,b){close_popup();var c=b["wordid[]"];typeof c!="object"&&(c=[c]);for(var d=0;d<c.length;d++)cleaner(c[d]+"_"+b.tagid,"tag")&&here.tagid==b.tagid&&cleaner(c[d],"word");c.length!=0&&do_info(la.info_tag_deleted)}function after_send_multi_addto_0_save(a,b){close_popup();var c=b["wordid[]"].length;c!=0&&do_info(c+" "+(c==1?la.info_word_addedto_save:la.info_words_addedto_save))}
function after_send_add_0_save(a,b){close_popup();b["wordid[]"].length!=0&&do_info(la.info_save_created)}function after_send_multi_removefrom_0_save(a,b){cleaner(b["wordid[]"],"word");a.count!=0&&do_info(a.count+" "+(a.count==1?la.info_word_removedfrom_save:la.info_words_removedfrom_save))}
function checkform(){try{var a=$("addword");if(a.newwordfirst.value=="")return do_info(la.err_231),a.newwordfirst.focus(),!1;else if(a.newwordfore.value=="")return do_info(la.err_232),a.newwordfore.focus(),!1;else{var b=validstr(a.newwordfirst.value),c=validstr(a.newwordfore.value);if(b>0)return do_info(la.err_invalidsyntax+"<\!-- "+b+" --\>"),a.newwordfirst.focus(),!1;else if(c>0)return do_info(la.err_invalidsyntax+"<\!-- "+c+" --\>"),a.newwordfore.focus(),!1}close_info();return!0}catch(d){return msg("[checkform]:"+
d),!1}}function action_add_word(){if(checkform()){var a=$("addword").serialize(!0);a.force=1;req("create_word",a,[resetform,after_send],{id:0,type:"word",action:"add",key:0})}}
function after_send_add_0_word(a){try{a.similar==1?(a.similarid.unshift(a.id),do_info(la.info_similar+" <span class='link' onclick='do_action("+Object.toJSON(a.similarid)+',"word","show")\'>'+la.compare+"</span>")):close_info();if(a.id==null)return!1;for(var b=["register","group","wordclass"],c=0;c<b.length;c++){var d={};d[b[c]+"id"]=a[b[c]];update_here(d)}a.taglist.count&&update_here({tagid:a.taglist.id[0]});update_hash();update_navigator();$("wordlist").show();$("lastlabel").show();appendwords({wordid:a.id},
0,1,1)}catch(e){msg("[after_send_add_0_word]"+e)}}action_addword_generic_show=action_addword_generic_overview=action_addword_generic_search=function(a,b){if(b){var c={};c[b+"id"]=a;update_here(c)}tab_switch("add")};
function resetform(){var a=$("addword");local.register=a.newregister.selectedIndex;local.group=a.newgroup.selectedIndex;local.wordfirst=a.newwordfirst.value;local.wordfore=a.newwordfore.value;local.satz=a.newsentence.value;local.tags=a.newtags.value;local.wordclass=a.newwordclass.selectedIndex;a.newwordfirst.value="";a.newwordfore.value="";a.newsentence.value="";a.newwordfirst.focus()}
function restoreform(){var a=$("addword");a.newwordfirst.value=local.wordfirst;a.newwordfore.value=local.wordfore;a.newsentence.value=local.satz;a.newtags.value=local.tags;a.newwordclass.selectedIndex=local.wordclass}
function update_add(){close_info();clear_here("wordid");var a=$("addword"),b=$(a.newregister).select('option[value="'+here.registerid+'"]')[0];if(b)b.selected=!0;if(b=$(a.newgroup).select('option[value="'+here.groupid+'"]')[0])b.selected=!0;a.newwordclass.selectedIndex=here.wordclassid;a.newwordfirst.focus();update_show()}function update_searchresult_show(){local.wordlist_complete=1;update_searchresult_search()}
function update_searchresult_search(){if(here.searchid=="")return tab_switch("show"),0;for(var a=local.current.subtext,b=local.current.searchresult,c=[],d=0;d<b.length;d++){var e=b[d];if(e[0]=="word"&&!(here.registerid&&local.as[a].word.registerid[e[2]]!=here.registerid)&&!$("wordlist_tr_"+local.as[a].word.id[e[2]])&&(c.push(local.as[a].word.id[e[2]]),c.length>50))break}c.length?(a={location:"php/wordtable.php","function":"wordform",json:1},a.parameters=Object.toJSON([{wordid:c},0,here.registerid?
0:1]),req("get_function",a,function(a){appendit(a.output);refresh_searchtab()})):refresh_searchtab()}function put_wordtable_line(a,b){try{var c=$("wordlist");if(!c)throw'[0] $("wordlist") is not defined';c=c.down("tbody");b<c.childNodes.length?Element.insert(c.childNodes[b],{before:a}):Element.insert(c,{bottom:a})}catch(d){msg("[put_wordtable_line]:"+d)}}
function refresh_searchtab(){try{var a=local.current.searchresult,b=local.current.subtext;if(!a)return 0;$$('[id^="wordlist_tr_"]').invoke("hide");for(var c=0,d=0;d<a.length;d++){var e=a[d];if(e[0]=="word"&&!(here.registerid&&local.as[b].word.registerid[e[2]]!=here.registerid)){var f=local.as[b].word.id[e[2]],g=$("wordlist_tr_"+f);g&&(put_wordtable_line(g,c),g.show(),c++)}}displaycolumn(here.registerid?0:1,"register");$("wordlist").show()}catch(h){msg("[refresh_searchtab]:"+h+" id: "+f),local.error=
{tr:g}}};function eventloader_showverblist(){$$('input[type="checkbox"][name^="all"]').each(function(a){a.onclick=function(){do_action(this.checked?1:0,this.readAttribute("name").substr(3),"checkall")}})}
function action_query_verb(){var a=$("verbqueryform").serialize(!0);if(!a.allverb&&!a["verbid[]"])return msg(la.err_210),0;if(!a.allform&&!a["formid[]"])return msg(la.err_207),0;if(!a.allperson&&!a["personid[]"])return msg(la.err_208),0;a.registerid=here.registerid;req("create_active_verb",a,function(a){if(a.count==0)return msg(la.err_250),0;document.location.href=path(2,{queryid:a.savedid})})}function action_checkall_generic(a,b){$$('input[name="'+b+'id[]"]').each(function(b){b.checked=a!=0})}
function rep_start(a){local.rep={};local.rep.selected=a;local.rep.startorder={};for(i=0;i<$("personlist").childNodes.length;i++)local.rep.startorder[Element.identify($("personlist").childNodes[i])]=i}function rep_end(){if(local.rep&&local.rep.selected!=null){var a=!0;for(i=0;i<$("personlist").childNodes.length;i++)local.rep.startorder[Element.identify($("personlist").childNodes[i])]!=i&&(a=!1);a||update_order();local.rep=null}}
function rep_change(a){if(local.rep&&local.rep.selected!=null&&local.rep.selected!=a){var b=$("personlist"),a=$("person_"+a),c=$("person_"+local.rep.selected),d=Object.values(b.childNodes);posnew=d.indexOf(a);posold=d.indexOf(c);where=posnew>posold?a.nextSibling:a;movenode=c.cloneNode(!0);b.removeChild(c);b.insertBefore(movenode,where)}}
function update_order(){var a=$("personlist").childNodes;for(i=0;i<a.length;i++){var b=Element.identify(a[i]),b=b.replace("person_","");req("edit_person",{personid:b,neworder:i})}};function read_count_id(a,b){var c=[],d=$$(a).each(function(a){c.push(a.identify().slice(b))}).length;return{id:c,count:d}}
function after_send_add_0_form_showverb(a){try{if(here.formid==null){for(var b={location:"php/wordtable.php","function":"wt_entry",json:1},c=0;c<a.count;c++)b.parameters="["+a.newid[c]+',"'+a.newname[c]+'","form",null,"form_'+a.newid[c]+'_remove",["show","hr","edit","delete"]]',req("get_function",b,function(a){appender(a.output,"form",$$(".tabhead")[0],"bottom")});if(here.wordid!=null)for(var d=read_count_id('[id^="tr_person_"]',10),c=0;c<a.count;c++)for(var e=0;e<d.count;e++)b.parameters='["v'+here.wordid+
"_p"+d.id[e]+"_f"+a.newid[c]+'","","kword",['+here.wordid+","+d.id[e]+","+a.newid[c]+'],"form_'+a.newid[c]+'_remove",["edit"]]',req("get_function",b,function(a,b,c){appender(a.output,"kword",$$("[id^='tr_person']")[c],"bottom")},e);else if(here.personid!=null)for(var f=read_count_id('[id^="tr_verb_"]',8),e=0;e<f.count;e++)b.parameters='["v'+f.id[e]+"_p"+here.personid+"_f"+a.newid+'","","kword",['+f.id[e]+","+here.personid+","+a.newid+'],"form_'+a.newid+'_remove",["edit"]]',req("get_function",b,function(a,
b,c){appender(a.output,"kword",$$("[id^='tr_verb']")[c],"bottom")},e)}close_popup()}catch(g){msg("[after_send_add_0_form]:"+g),errnum=1}}
function after_send_add_0_person_showverb(a){try{if(here.person==null){var b={json:1};if(here.wordid!=null){b.location="php/verbtable.php";b["function"]="writeverbline";for(var c=read_count_id('td[id^="form_"]',5),d=0;d<a.count;d++)b.parameters=Object.toJSON([0,{id:here.wordid,what:"verb"},{what:"form",id:c.id,count:c.count},{what:"person",id:[a.newid[d]],name:[a.newname[d]]},null]),req("get_function",b,function(a){appender(a.output,"person",$("wordlist").down(),"bottom")})}else if(here.formid!=null){b.location=
"php/wordtable.php";b["function"]="wt_entry";for(c=0;c<a.count;c++)b.parameters="["+a.newid[c]+',"'+a.newname[c]+'","person",null,"person_'+a.newid[c]+'_remove",["show","hr","edit","delete"]]',req("get_function",b,function(a){appender(a.output,"kword",$$(".tabhead")[0],"bottom")});for(var e=read_count_id('[id^="tr_verb_"]',8),c=0;c<a.count;c++)for(d=0;d<e.count;d++)b.parameters='["v'+e.id[d]+"_p"+a.newid[c]+"_f"+here.formid+'","","kword",['+e.id[d]+","+a.newid[c]+","+here.formid+'],"person_'+a.newid[c]+
'_remove",["edit"]]',req("get_function",b,function(a,b,c){appender(a.output,"kword",$$("[id^='tr_verb']")[c],"bottom")},d)}}close_popup()}catch(f){msg("[after_send_add_0_person]:"+f),errnum=1}}function input_keydown_38_kword(){send_input()}function after_send_edit_38_kword(a,b){after_send_edit_13_kword(a,b);var c=local.current.where.up().previousSiblings().size(),d=local.current.where.up().up().previous();d&&(d=d.down("td",c).down());if(d)d.ondblclick()}
function input_keydown_40_kword(){send_input()}function after_send_edit_40_kword(a,b){after_send_edit_13_kword(a,b);var c=local.current.where.up().previousSiblings().size(),d=local.current.where.up().up().next();d&&(d=d.down("td",c).down());if(d)d.ondblclick()};function queryedit(a,b){var c;qe.mode=="0"||qe.mode=="2"?c=b==0?"wordfirst":"wordfore":qe.mode=="1"||qe.mode=="3"?c=b==1?"wordfirst":"wordfore":qe.mode=="4"&&(c=b==1?"kword":!1);c&&do_action(qe.gone.id,c,"edit",a)}action_edit_wordfirst_query=action_edit_wordfore_query=action_edit_kword_query=function(a,b,c){action_edit_generic(a,b,c,!1,c.innerHTML)};
function send_edit_kword_query(a){var b=$("input_edit");b&&req("edit_verb",{verbid:a,newkword:b.value},after_send,{id:a,type:"kword",action:"edit",key:13})}after_send_edit_13_wordfirst_query=after_send_edit_13_wordfore_query=after_send_edit_13_kword_query=function(a,b,c,d){qe.updatelast();close_action("edit",d)};function querysave(a){rvar.create("savequery","query_save",{registerid:here.registerid,queryid:here.queryid,wrong:a},close_popup);show_error_104_query_save(!0)}
function show_error_104_query_save(a){var b=new formparam("querysave");b.addinput("newsavename","name");if(a!==!0)b.error="err_duplicatesave";request_form("savequery",b)};function change_settings(){do_shutter(1);var a=$("settings_form").serialize(!0);req("change_options",a,function(a){a.errnum==0?location.reload():la["err_"+a.errnum]&&do_info(la["err_"+a.errnum])})}
function change_password(){do_shutter(1);var a=$("password_form").serialize(!0),b;if(a.newpassword){if(a.newpassword!=a.checkpassword)b=la.err_password}else b=la.err_234;if(b)return do_info(b),close_shutter(),!1;req("change_password",a,function(a){a.success!=1?(do_info(la.err_wrongpass),$("password_form").oldpassword.focus()):a.errnum==0?do_info(la.info_settings_changed):la["err_"+a.errnum]&&do_info(la["err_"+a.errnum]);close_shutter()})};function initializer_content(){var a=$("login_form");if(a)a.onsubmit=function(){return validate_login_form()};if(a=$("nregister_form"))a.onsubmit=function(){return validate_nregister_form()};if(a=$("forgot_form"))a.onsubmit=function(){return validate_forgot_form()}}function validate_login_form(a){a=a||$("login_form");if(!a)return!1;if(a.username.value){if(!a.password.value)return do_info(la.err_234),!1}else return do_info(la.err_237),!1;return!0}
function validate_nregister_form(){var a=$("nregister_form");if(!a)return!1;if(a.email.value)if(a.passwordrepeat.value)if(a.passwordrepeat.value!==a.password.value)return do_info(la.err_password),!1;else{if(!a.accept.checked)return do_info(la.err_accept),!1}else return do_info(la.err_236),!1;else return do_info(la.err_238),!1;return validate_login_form(a)}
function validate_forgot_form(){var a=$("forgot_form");if(!a)return!1;if(!a.email.value&&!a.username.value)return do_info(la.err_200),!1;return!0};
